services:
  # Servicio de la API
  api:
    build:
      context: .
      dockerfile: Dockerfile
    
    container_name: devops-api
    
    ports:
      - "3000:3000"
    
    environment:
      - NODE_ENV=production
      - PORT=3000
      - SENTRY_DSN=${SENTRY_DSN}
    
    restart: unless-stopped
    
    # Healthcheck para verificar que la API está funcionando
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
      
    # Servicio de Prometheus
  prometheus:
    image: prom/prometheus:latest
    
    container_name: prometheus
    
    ports:
      - "9090:9090"
    
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    
    restart: unless-stopped
    
  # Servicio de Grafana
  grafana:
    image: grafana/grafana:latest
    
    container_name: grafana
    
    ports:
      - "3001:3000"
    
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    
    volumes:
      - grafana_data:/var/lib/grafana
    
    restart: unless-stopped
    
    depends_on:
      - prometheus

volumes:
  prometheus_data:
  grafana_data:

